### ISSUE TITLE
go.mod support

### ISSUE THREAD

**Issue by diamondburned** [eliukblau/pixterm#10]
Since Go 1.12 is out, I think this repository should have a go.mod file. I could do a PR if you want.

**Comment by diamondburned** [comment]
Couldn't wait: https://github.com/eliukblau/pixterm/pull/12

**Comment by eliukblau** [comment]
https://github.com/eliukblau/pixterm/pull/12#issuecomment-487458454

**Comment by eliukblau** [comment]
Solved in [v1.3.0](https://github.com/eliukblau/pixterm/releases/tag/v1.3.0)
