### ISSUE TITLE
Draw animated gifs

### ISSUE THREAD

**Issue by mattLLVW** [eliukblau/pixterm#20]
I'm using pixterm to convert animated gifs for my project: https://github.com/mattLLVW/e.xec.sh

Would you be interested in a PR adding this functionality?

**Comment by eliukblau** [comment]
Of course! Do the PR on "animgif" branch so I can check if it is applicable.
👍 Thanks for contributing!

**Comment by eliukblau** [comment]
Closed due to inactivity.
