### ISSUE TITLE
apple  (arm64) m1 device cannot compile

### ISSUE THREAD

**Issue by 4cecoder** [eliukblau/pixterm#21]
### terminal input
```shell
go mod tidy
go run cmd/pixterm/pixterm.go
```

### error output:
```shell
# command-line-arguments
cmd/pixterm/pixterm.go:64:3: undefined: printIcon
cmd/pixterm/pixterm.go:68:2: undefined: printContributors
```
### For some odd reason there's an issue within `func printCredits()` 
 `printIcon()` & `printContributers()` are out of scope therefore unreachable

if you comment out `printIcon()` & `printContributers()`  within `func printCredits()` then it builds successfully

**Comment by 4cecoder** [comment]
error output updated

**Comment by 4cecoder** [comment]
error output updated

**Comment by eliukblau** [comment]
Related https://github.com/eliukblau/pixterm/pull/22

**Comment by eliukblau** [comment]
Hi! Thanks for your observations. What's the version of `golang.org/x/sys` that you say compiles correctly on Apple M1?

**Comment by eliukblau** [comment]
Independent of what was mentioned in https://github.com/eliukblau/pixterm/pull/22, the correct way to `go run` CLI app is:

- if you are in the root of project: `go run ./cmd/pixterm/` or `go run ./cmd/pixterm/.`
- if you are in the inner `cmd/pixterm` directory: `go run .`

**Comment by eliukblau** [comment]
Closed due inactivity

**Comment by eliukblau** [comment]
Closed due inactivity
