### ISSUE TITLE
Can't build due compile time error

### ISSUE THREAD

**Issue by lukasmalkmus** [eliukblau/pixterm#5]
I tried to vendor the `ansimage` package using [dep](https://github.com/golang/dep). But when compiling my project I see two errors of kind `multiple-value colorful.MakeColor() in single-value context` in those lines:

https://github.com/eliukblau/pixterm/blob/a39660c811b7075c5de15f35350f27d6d4dfe630/ansimage/ansimage.go#L466-L467

The error makes perfect sense, but I don't get what went wrong here. You may have used a very old version of `go-colorful`. Check out the [releases](https://github.com/lucasb-eyer/go-colorful/releases), I might make sense to update your glide config tot use the `1.0` release.

**Comment by eliukblau** [comment]
@lukasmalkmus Yeah. Probably old versions of packages. Thank for observe this. For the moment, I'm evaluating replace Glide with vgo, which will become the default dependency manager for Go.

I will leave this issue open until I change the dependency manager.

**Comment by lmorg** [comment]
Regardless of package dependency, this is a pretty simple fix. I've included a PR: https://github.com/eliukblau/pixterm/pull/9

Thanks for the good work on this, by the way. I use this package heavily in one of my own projects.

**Comment by eliukblau** [comment]
PR #9 merged :) But this will be released in the upcoming version ;)

**Comment by eliukblau** [comment]
Solved in [v1.3.0](https://github.com/eliukblau/pixterm/releases/tag/v1.3.0)
