### ISSUE TITLE
Transparent bacground

### ISSUE THREAD

**Issue by drkmrin78** [eliukblau/pixterm#7]
Is there a way to make the background transparent? as in not black or white, but transparent with the terminal. I really want some images turned to ascii with colors but let the background be transparent like my terminal. Your tool does the best job with colors and gradients from what I've seen.

**Comment by eliukblau** [comment]
Yeah :) This does the trick: simply add `-m` argument with a color that match your terminal background. Color is in HEX format. "Real" transparent background based on alpha channel (as in iTerm or another sofisticated terminal apps) is not representable trough ANSI color codes, sorry.

[Check this screenshot](https://github.com/eliukblau/pixterm/blob/master/screenshot01.png) about CLI arguments ;)

**Comment by drkmrin78** [comment]
Yeah I was hoping there was a way to print without changing the background colors at all so that the transparency would persistent. I might be able to trick the terminal by setting the transparency after printing the image. Thank you!
